In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats

In [2]:
## Import files "written"
written_train = np.load("written_train.npy", allow_pickle=True)

# # Import files "spoken"
spoken_train = np.load('spoken_train.npy', allow_pickle=True)

# # Import file "match"
match_train = np.load('match_train.npy', allow_pickle=True)

written_corner = np.load('image_hoek.npy', allow_pickle=True)
plasma_sd = np.load('plasma_sd_Z.npy', allow_pickle=True)
plasma_m = np.load('plasma_mean_Z.npy', allow_pickle=True)

In [3]:
target = []
indexes_true = []
indexes_false = []
                       
for i, j in enumerate(match_train):
    if j == True:
        target.append(2)
        indexes_true.append(i)
    elif j == False:
        target.append(1)
        indexes_false.append(i)
        
false_included = indexes_false[:6000]
included_rows = indexes_true + false_included

In [18]:
## MEANS
written_means = []
for i in written_train:
    written_means.append(np.mean(i))

spoken_means = []
for i in spoken_train:
    spoken_means.append(np.mean(i))
    
## COUNT OF DARK PIXELS
dark_pixels = []
for i in written_train:
    dark_pixels_count = 0
    for j in i:
        if j < 50:
            dark_pixels_count += 1
    dark_pixels.append(dark_pixels_count)
    
## LENGTH
spoken_length = []

for i in spoken_train:
    spoken_length.append(len(i))
    
## LENGTH 2 standardize
spoken_length2 = []

for i in spoken_train:
    spoken_length2.append(len(i))
    
spoken_length2 = stats.zscore(spoken_length2)
    
## MINIMUM
written_min = []
for i in written_train:
    written_min.append(np.amin(i))

spoken_min = []
for i in spoken_train:
    spoken_min.append(np.amin(i))
    
## MAXIMUM
written_max = []
for i in written_train:
    written_max.append(np.amax(i))

spoken_max = []
for i in spoken_train:
    spoken_max.append(np.amax(i))
    
## GLOBAL MEAN
written_global = np.mean(written_train)
spoken_global = np.mean(spoken_means)

## STANDARD DEVIATION (PER MEAN OF ARRAY)
# written_sd = []

# for i in written_means:
#     x = np.sqrt(written_global* ((i-(written_global*i))**2))
#     written_sd.append(x)

# spoken_sd = []

# for i in spoken_means:
#     x = np.sqrt(spoken_global*((i-(spoken_global*i))**2))
#     spoken_sd.append(x)
    
# print(written_sd)
# print(spoken_sd)


In [20]:
mean_1 = []
mean_2 = []
mean_3 = []
mean_4 = []
mean_5 = []
mean_6 = []
mean_7 = []
mean_8 = []
mean_9 = []
mean_10 = []
mean_11 = []
mean_12 = []
mean_13 = []
for i in spoken_train:
    for w in range(0,13):
        if w ==0:
            mean_1.append(np.mean(i[:,w]))
        elif w == 1:
            mean_2.append(np.mean(i[:,w]))
        elif w == 2:
            mean_3.append(np.mean(i[:,w]))
        elif w == 3:
            mean_4.append(np.mean(i[:,w]))
        elif w == 4:
            mean_5.append(np.mean(i[:,w]))
        elif w == 5:
            mean_6.append(np.mean(i[:,w]))
        elif w == 6:
            mean_7.append(np.mean(i[:,w]))
        elif w == 7:
            mean_8.append(np.mean(i[:,w]))
        elif w == 8:
            mean_9.append(np.mean(i[:,w]))
        elif w == 9:
            mean_10.append(np.mean(i[:,w]))
        elif w == 10:
            mean_11.append(np.mean(i[:,w]))
        elif w == 11:
            mean_12.append(np.mean(i[:,w]))
        elif w == 12:
            mean_13.append(np.mean(i[:,w]))      

In [52]:
SD_1 = []
SD_2 = []
SD_3 = []
SD_4 = []
SD_5 = []
SD_6 = []
SD_7 = []
SD_8 = []
SD_9 = []
SD_10 = []
SD_11 = []
SD_12 = []
SD_13 = []
for i in spoken_train:
    for w in range(0,13):
        if w ==0:
            SD_1.append(np.std(i[:,w]))
        elif w == 1:
            SD_2.append(np.std(i[:,w]))
        elif w == 2:
            SD_3.append(np.std(i[:,w]))
        elif w == 3:
            SD_4.append(np.std(i[:,w]))
        elif w == 4:
            SD_5.append(np.std(i[:,w]))
        elif w == 5:
            SD_6.append(np.std(i[:,w]))
        elif w == 6:
            SD_7.append(np.std(i[:,w]))
        elif w == 7:
            SD_8.append(np.std(i[:,w]))
        elif w == 8:
            SD_9.append(np.std(i[:,w]))
        elif w == 9:
            SD_10.append(np.std(i[:,w]))
        elif w == 10:
            SD_11.append(np.std(i[:,w]))
        elif w == 11:
            SD_12.append(np.std(i[:,w]))
        elif w == 12:
            SD_13.append(np.std(i[:,w]))

In [53]:
import pandas as pd
index = range(0,len(written_train))
#columns = ['Mean written', 'Mean spoken', 'Length spoken', 'Minimum written', 'Minimum spoken', 'Maximum written', 'Maximum spoken', 'Target']
#columns = ['Mean written', 'Mean spoken', 'Length spoken', 'Minimum spoken', 'Maximum spoken', 'Target']
#columns = ['Mean written', 'Length spoken', 'Minimum spoken', 'Maximum spoken', 'Target']
columns = ['Mean written', 'Corners written','Plasma sd', 'Length spoken', 'Minimum spoken', 'Maximum spoken', \
           'mean_1','mean_2','mean_3','mean_4','mean_5','mean_6','mean_7','mean_8','mean_9','mean_10','mean_11',\
           'mean_12','mean_13','SD_1','SD_2','SD_3','SD_4','SD_5','SD_6','SD_7','SD_8','SD_9','SD_10','SD_11',\
           'SD_12','SD_13','Target']


df_a = pd.DataFrame(index=index, columns=columns)
df_a['Mean written'] = written_means
#df_a['Dark pixels written'] = dark_pixels
df_a['Corners written'] = written_corner
#df_a['Plasma mean'] = plasma_m
df_a['Plasma sd'] = plasma_sd
#df_a['Mean spoken'] = spoken_means
df_a['Length spoken'] = spoken_length
#df_a['Minimum written'] = written_min
df_a['Minimum spoken'] = spoken_min
#df_a['Maximum written'] = written_max
df_a['Maximum spoken'] =  spoken_max
df_a['mean_1'] =  mean_1
df_a['mean_2'] =  mean_2
df_a['mean_3'] =  mean_3
df_a['mean_4'] =  mean_4
df_a['mean_5'] =  mean_5
df_a['mean_6'] =  mean_6
df_a['mean_7'] =  mean_7
df_a['mean_8'] =  mean_8
df_a['mean_9'] =  mean_9
df_a['mean_10'] =  mean_10
df_a['mean_11'] =  mean_11
df_a['mean_12'] =  mean_12
df_a['mean_13'] =  mean_13
df_a['SD_1'] =  SD_1
df_a['SD_2'] =  SD_2
df_a['SD_3'] =  SD_3
df_a['SD_4'] =  SD_4
df_a['SD_5'] =  SD_5
df_a['SD_6'] =  SD_6
df_a['SD_7'] =  SD_7
df_a['SD_8'] =  SD_8
df_a['SD_9'] =  SD_9
df_a['SD_10'] =  SD_10
df_a['SD_11'] =  SD_11
df_a['SD_12'] =  SD_12
df_a['SD_13'] =  SD_13
df_a['Target'] = target


df_a


Mean written  Corners written  Plasma sd  Length spoken  \
0        222.764031              2.0  -0.423996             41   
1        237.927296              1.0   1.145061             33   
2        241.182398              2.0   0.956602             25   
3        222.052296              4.0   0.707761             40   
4        215.610969              4.0  -0.866517             38   
5        205.534439              5.0  -0.617600             28   
6        239.442602              2.0   1.055377             32   
7        219.184949              3.0   0.294313             35   
8        225.914541              1.0  -0.488373             38   
9        229.280612              3.0  -0.595049             56   
10       227.470663              3.0   0.591767             44   
11       215.822704              5.0   0.156616             43   
12       232.766582              2.0   0.923523             42   
13       231.427296              5.0  -0.016684             32   
14       230.646684              2.0   1.255950             34   
15       237.876276              3.0   1.239754             34   
16       200.229592              6.0  -1.778822             33   
17       233.218112              6.0   0.070963             47   
18       225.153061              3.0  -0.116115             46   
19       228.372449              2.0  -0.034919             46   
20       227.771684              3.0  -0.064142             48   
21       230.987245              2.0   1.134658             56   
22       229.852041              2.0   0.390237             35   
23       218.580357              3.0  -0.205165             58   
24       225.387755              4.0   0.799801             24   
25       216.445153              6.0  -0.648442             49   
26       219.267857              5.0  -0.907295             37   
27       223.367347              3.0  -0.430553             40   
28       191.360969              6.0  -1.572164             37   
29       231.448980              4.0   0.340377             31   
...             ...              ...        ...            ...   
44970    226.188776              5.0  -1.081292             49   
44971    220.285714              1.0   0.104625             41   
44972    220.113520              4.0   0.376360             31   
44973    200.830357              3.0  -0.390663             53   
44974    236.774235              2.0   1.271973             32   
44975    213.437500              6.0   0.042110             39   
44976    217.262755              2.0  -0.786443             21   
44977    209.734694              4.0   1.829844             46   
44978    211.420918              3.0   0.391993             41   
44979    226.447704              4.0   0.034612             35   
44980    198.830357              4.0  -1.497557             53   
44981    215.082908              7.0  -0.684182             46   
44982    205.536990              5.0  -0.362293             39   
44983    224.140306              6.0  -0.350782             37   
44984    242.080357              2.0   0.553523             58   
44985    216.720663              4.0   0.060548             40   
44986    230.678571              2.0   1.672454             41   
44987    222.539541              3.0  -0.023870             40   
44988    223.846939              6.0   0.161871             40   
44989    224.501276              3.0  -0.516780             35   
44990    224.201531              5.0  -1.066343             54   
44991    214.396684              4.0  -0.127448             37   
44992    238.072704              2.0   1.154190             39   
44993    225.251276              4.0  -1.078849             22   
44994    218.832908              6.0  -1.110788             60   
44995    224.988520              5.0   0.869189             39   
44996    215.355867              4.0  -0.944056             39   
44997    211.178571              3.0  -0.529766             44   
44998    204.825255              6.0   0.125757

In [54]:
# Split data into X's (summaries) and y (which is the target value)

X = df_a.iloc[included_rows, 0:32].values
y = df_a.iloc[included_rows, 32].values

In [55]:

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2)

In [56]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

# Instantiate model 
rf = RandomForestRegressor(n_estimators= 1000, random_state=42)

# Train the model on training data
rf.fit(X_train, y_train);

In [ ]:
rf_new = RandomForestRegressor(n_estimators = 100, criterion = 'entropy', max_depth = None, 
                               min_samples_split = 2, min_samples_leaf = 1)

In [57]:
# Use the forest's predict method on the test data
predictions = rf.predict(X_val)

# Calculate the absolute errors
errors = abs(predictions - y_val)

# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')


Mean Absolute Error: 0.43 degrees.


In [58]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_val)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 67.75 %.


In [59]:
count_true = 0
count_false = 0
for i in y_val:
    if i == 1:
        count_false += 1
    else:
        count_true += 1

In [60]:
print(count_false)

1177


In [61]:
count_true/(count_true+count_false)

0.4416508538899431

In [62]:
index = range(0,len(y_val))
columns = ['predictions', 'y_val']


df_b = pd.DataFrame(index=index, columns=columns)
df_b['predictions'] = predictions
df_b['y_val'] = y_val


df_b


predictions  y_val
0           1.439      2
1           1.142      1
2           1.307      1
3           1.255      1
4           1.167      1
5           1.218      1
6           1.478      1
7           1.236      1
8           1.684      2
9           1.855      1
10          1.102      1
11          1.525      2
12          1.117      1
13          1.455      1
14          1.498      2
15          1.567      2
16          1.482      2
17          1.674      1
18          1.152      2
19          1.647      2
20          1.372      1
21          1.372      1
22          1.489      2
23          1.562      2
24          1.388      2
25          1.297      1
26          1.652      2
27          1.485      2
28          1.360      1
29          1.309      1
...           ...    ...
2078        1.290      1
2079        1.443      2
2080        1.270      1
2081        1.508      2
2082        1.245      2
2083        1.706      1
2084        1.370      1
2085        1.451      1
2086        1.359      2
2087        1.421      1
2088        1.271      1
2089        1.337      1
2090        1.679      1
2091        1.335      1
2092        1.244      1
2093        1.296      2
2094        1.139      1
2095        1.770      2
2096        1.430      2
2097        1.231      1
2098        1.290      1
2099        1.380      2
2100        1.400      2
2101        1.309      1
2102        1.558      2
2103        1.321      1
2104        1.088      1
2105        1.458      1
2106        1.274      1
2107        1.494      1

[2108 rows x 2 columns]

In [63]:
y_pred = np.array(df_b["predictions"])

In [64]:
for index, value in enumerate(y_pred):
    if value >= 1.5:
        y_pred[index] = 2
    else: y_pred[index] = 1

In [42]:
y_pred

array([2., 1., 1., ..., 2., 1., 2.])

In [65]:
## TN, FP
## FN, TP
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_val, y_pred)
print(cm)

[[893 284]
 [489 442]]


In [66]:
#[[922 231]
# [480 475]]

In [49]:
count_false

1153

In [50]:
count_false +count_true 

2108

In [51]:
922+231+480+475

2108